#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

OFFLINE_CORES=8

JS_TEST=../../../../../tests/pitzDaily
JS_TEST_DATA=${JS_TEST}/data
JS_TEST_MATRICES=${JS_TEST_DATA}/matrices

cleanCase
rm -r ITHACAoutput
rm -r runs
blockMesh > log.blockMesh 2>&1
./run_offline.sh $OFFLINE_CORES
#foamJob -screen steady
foamJob -screen steady -online -U 1.5 -nu 0.00005
(cd ITHACAoutput/Reconstruction && \
 rm 0 && \
 ln -s ../../0 0 && \
 rm constant && \
 ln -s ../../constant constant && \
 rm system && \
 ln -s ../../system system && \
 mv 1 3 )
foamJob -screen steady -online -U 10.0 -nu 0.00001
(cd ITHACAoutput/Reconstruction && mv 1 2)
foamJob -screen steady -online -U 15.0 -nu 0.0001
mv 1 U_15_nu_0-0001
foamToVTK -case ITHACAoutput/Reconstruction
touch ITHACAoutput/Offline/foam.foam
touch ITHACAoutput/Reconstruction/foam.foam
foamToVTK -ascii -time 0 -fields 'none' -no-point-data

if [ ! -d $JS_TEST_DATA ];then
  mkdir -p $JS_TEST_DATA
fi

if [ ! -d $JS_TEST_MATRICES ];then
  mkdir -p $JS_TEST_MATRICES
fi

cp ITHACAoutput/Matrices/P_mat.txt $JS_TEST_MATRICES/
cp ITHACAoutput/Matrices/M_mat.txt $JS_TEST_MATRICES/
cp ITHACAoutput/Matrices/K_mat.txt $JS_TEST_MATRICES/
cp ITHACAoutput/Matrices/B_mat.txt $JS_TEST_MATRICES/
cp ITHACAoutput/Matrices/coeffL2_mat.txt $JS_TEST_MATRICES/
cp ITHACAoutput/Matrices/C/C*_mat.txt $JS_TEST_MATRICES/
cp ITHACAoutput/Matrices/ct1/ct1*_mat.txt $JS_TEST_MATRICES/
cp ITHACAoutput/Matrices/ct2/ct2*_mat.txt $JS_TEST_MATRICES/
cp ITHACAoutput/Parameters/par.txt ${JS_TEST_DATA}/
cp ITHACAoutput/POD/EigenModes_U_mat.txt ${JS_TEST_DATA}/
cp VTK/*/internal.vtu ${JS_TEST_DATA}/pitzDaily.vtu
